data_path: /gpfs/alpine/world-shared/bip216/ddmd_westpa/data/preprocessed/spike-all-AAE.h5
output_path: /gpfs/alpine/world-shared/bip216/ddmd_westpa/runs/aae_runs/tmp
init_weights: null
dataset_name: point_cloud
rmsd_name: rmsd
fnc_name: rmsd
num_points: 3375
num_features: 0
epochs: 100
batch_size: 32
optimizer_name: Adam
optimizer_lr: 0.0001
latent_dim: 64
encoder_filters:
- 64
- 128
- 256
- 256
- 512
encoder_kernel_sizes:
- 5
- 5
- 3
- 1
- 1
generator_filters:
- 64
- 128
- 512
- 1024
discriminator_filters:
- 512
- 512
- 128
- 64
encoder_relu_slope: 0.0
generator_relu_slope: 0.0
discriminator_relu_slope: 0.0
use_encoder_bias: true
use_generator_bias: true
use_discriminator_bias: true
noise_mu: 0.0
noise_std: 1.0
lambda_rec: 0.5
lambda_gp: 10.0
embed_interval: 10
checkpoint_interval: 10
sample_interval: 5
num_data_workers: 0
dataset_location: storage
